// Generated by gencpp from file persons_msgs/Rotation.msg
// DO NOT EDIT!


#ifndef PERSONS_MSGS_MESSAGE_ROTATION_H
#define PERSONS_MSGS_MESSAGE_ROTATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace persons_msgs
{
template <class ContainerAllocator>
struct Rotation_
{
  typedef Rotation_<ContainerAllocator> Type;

  Rotation_()
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
    }
  Rotation_(const ContainerAllocator& _alloc)
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _r_type;
  _r_type r;

   typedef double _p_type;
  _p_type p;

   typedef double _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::persons_msgs::Rotation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::persons_msgs::Rotation_<ContainerAllocator> const> ConstPtr;

}; // struct Rotation_

typedef ::persons_msgs::Rotation_<std::allocator<void> > Rotation;

typedef boost::shared_ptr< ::persons_msgs::Rotation > RotationPtr;
typedef boost::shared_ptr< ::persons_msgs::Rotation const> RotationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::persons_msgs::Rotation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::persons_msgs::Rotation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace persons_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'persons_msgs': ['/home/uema/catkin_ws/src/persons_msgs/msg', '/home/uema/catkin_ws/src/persons_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::persons_msgs::Rotation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::persons_msgs::Rotation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::persons_msgs::Rotation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::persons_msgs::Rotation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::persons_msgs::Rotation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::persons_msgs::Rotation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::persons_msgs::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5585e6b09b13f56ed964334fed50470";
  }

  static const char* value(const ::persons_msgs::Rotation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5585e6b09b13f56ULL;
  static const uint64_t static_value2 = 0xed964334fed50470ULL;
};

template<class ContainerAllocator>
struct DataType< ::persons_msgs::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "persons_msgs/Rotation";
  }

  static const char* value(const ::persons_msgs::Rotation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::persons_msgs::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n\
float64 p\n\
float64 y\n\
";
  }

  static const char* value(const ::persons_msgs::Rotation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::persons_msgs::Rotation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.p);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Rotation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::persons_msgs::Rotation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::persons_msgs::Rotation_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERSONS_MSGS_MESSAGE_ROTATION_H
